In [275]:
import json

## Exercise1: Point Feature
Create a simple Point feature for San Francisco. Include 2 properties: name and country. The coordinates are -122.4194, 37.7749.

In [276]:
coords, name, country = [-122.4194, 37.7749], 'San Francisco', 'USA'
point_feature_template = {
    'type': 'Feature',
    'geometry':{
        'type': 'Point',
        'coordinates': coords
    },
    'properties':{
        'name': name,
        'country': country
    }
}
print(point_feature_template)

{'type': 'Feature', 'geometry': {'type': 'Point', 'coordinates': [-122.4194, 37.7749]}, 'properties': {'name': 'San Francisco', 'country': 'USA'}}


## Exercise2: FeatureCollection
Create a FeatureCollection with Point features for three cities: New York (-74.006, 40.7128), Los Angeles (-118.2437, 34.0522), and Chicago (-87.6298, 41.8781). Use list comprehension to create the features.

In [277]:
cities = [('New York', [-74.006, 40.7128]),('Los Angeles',[-118.2437, 34.0522]),('Chicago', [-87.6298, 41.8781])]

feature_collection = {
    "type": "FeatureCollection",
    "features": []
}

for cityName, coords in cities:
    point_feature_template1 = {
        "type": "Feature",
        "geometry":{
            "type": "Point",
            "coordinates": coords
        },
        "properties":{
            "name": cityName
            #"population": 5402499
        }
    }
    feature_collection['features'].append(point_feature_template1)

# print the featurecollection string with indent=2
str_feature_collection = json.dumps(feature_collection, indent=2)
print(str_feature_collection)

# check the feature count
print(f"\nThe number of features are {len(feature_collection['features'])}.")

{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -74.006,
          40.7128
        ]
      },
      "properties": {
        "name": "New York"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -118.2437,
          34.0522
        ]
      },
      "properties": {
        "name": "Los Angeles"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -87.6298,
          41.8781
        ]
      },
      "properties": {
        "name": "Chicago"
      }
    }
  ]
}

The number of features are 3.


In [278]:
'''
Create the FeatureCollection using list comprehension
Basic List Comprehension: [expression for item in iterable]

Advantages of using List Comprehension:

- More concise code
- More readable (once you're familiar with the syntax)
- Generally better performance
- More Pythonic (follows Python's coding style conventions)

This style is particularly suitable for:

- Creating new lists based on an iterable  --> Geojson['feature'] is a list containing multiple features objects(dict).
- When each element needs the same transformation  --> Features in the list "cities" are all Point.
- Uniform data structures  --> The feature object in a featurecollection object has the same Geojson struture.
- Simple transformations without complex conditions (although list comprehensions do support conditions)
'''

feature_collection1 = {
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": coords  # Note: GeoJSON uses [longitude, latitude] order
            },
            "properties": {
                "name": name
            }
        }
        for name, coords in cities  # This is the list comprehension part
    ]
}

print(feature_collection1)
print("\n",feature_collection1.keys())
print("\n",[ ele['properties']['name'] for ele in feature_collection1['features']])

{'type': 'FeatureCollection', 'features': [{'type': 'Feature', 'geometry': {'type': 'Point', 'coordinates': [-74.006, 40.7128]}, 'properties': {'name': 'New York'}}, {'type': 'Feature', 'geometry': {'type': 'Point', 'coordinates': [-118.2437, 34.0522]}, 'properties': {'name': 'Los Angeles'}}, {'type': 'Feature', 'geometry': {'type': 'Point', 'coordinates': [-87.6298, 41.8781]}, 'properties': {'name': 'Chicago'}}]}

 dict_keys(['type', 'features'])

 ['New York', 'Los Angeles', 'Chicago']


## Exercise3: LineString Feature
Create a LineString feature representing a flight path from San Francisco to New York to London. Use the coordinates: San Francisco (-122.4194, 37.7749), New York (-74.006, 40.7128), and London (-0.1276, 51.5074). Add a property "name" with the value "International Flight Path".

In [279]:
name = "International Flight Path"
coords = [[-122.4194, 37.7749], [-74.006, 40.7128], [-0.1276, 51.5074]]

LineString_feature_template = {
    'type': 'Feature',
    'geometry':{
        'type': 'LineString',
        'coordinates': coords  # same array structure [ [lon,lat], [lon,lat], ... ] as MultiPoint
    },
    'properties':{
        'name': name,
    }
}

str_LineString_feature = json.dumps(LineString_feature_template, indent=2)
print(str_LineString_feature)

{
  "type": "Feature",
  "geometry": {
    "type": "LineString",
    "coordinates": [
      [
        -122.4194,
        37.7749
      ],
      [
        -74.006,
        40.7128
      ],
      [
        -0.1276,
        51.5074
      ]
    ]
  },
  "properties": {
    "name": "International Flight Path"
  }
}


## Exercise4: Polygon Feature
Create a Polygon feature representing the approximate boundaries of Golden Gate Park in San Francisco. Use these coordinates for the polygon:
[(-122.4194, 37.7749), (-122.4099, 37.7912), (-122.3984, 37.7860), (-122.4082, 37.7694), (-122.4194, 37.7749)]
Add a property "name" with the value "Golden Gate Park".

In [280]:
coords = [(-122.4194, 37.7749), (-122.4099, 37.7912), (-122.3984, 37.7860), (-122.4082, 37.7694), (-122.4194, 37.7749)]
coords_new = [[lon, lat] for lon, lat in coords]

print(coords_new)

[[-122.4194, 37.7749], [-122.4099, 37.7912], [-122.3984, 37.786], [-122.4082, 37.7694], [-122.4194, 37.7749]]


In [281]:
name = "Golden Gate Park"

polygon_feature_template = {
    'type': 'Feature',
    'geometry':{
        'type': 'Polygon',
        'coordinates': [  # First array: for multiple linear rings (outer ring and optional holes)
            coords_new  # Second array: list of positions
        ]
    },
    'properties':{
        'name': name,
    }
}
str_polygon_feature = json.dumps(polygon_feature_template, indent=2)
print(str_polygon_feature)

{
  "type": "Feature",
  "geometry": {
    "type": "Polygon",
    "coordinates": [
      [
        [
          -122.4194,
          37.7749
        ],
        [
          -122.4099,
          37.7912
        ],
        [
          -122.3984,
          37.786
        ],
        [
          -122.4082,
          37.7694
        ],
        [
          -122.4194,
          37.7749
        ]
      ]
    ]
  },
  "properties": {
    "name": "Golden Gate Park"
  }
}


## Exercise5: Add elevation data
Use dictionary comprehension to add elevation data to the cities from exercise 2. Elevation data: San Francisco (16m), New York (10m), Los Angeles (89m), Chicago (182m).

In [282]:
list_cityName = [x['properties']['name'] for x in feature_collection['features']]
list_cityName

['New York', 'Los Angeles', 'Chicago']

In [283]:
elevation_data = [10, 89, 182]
i = 0
for ele in feature_collection['features']:
    ele['geometry']['coordinates'].append(elevation_data[i])
    print(ele['geometry']['coordinates'])
    i += 1

[-74.006, 40.7128, 10]
[-118.2437, 34.0522, 89]
[-87.6298, 41.8781, 182]


In [284]:
print (json.dumps(feature_collection, indent=2))

{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -74.006,
          40.7128,
          10
        ]
      },
      "properties": {
        "name": "New York"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -118.2437,
          34.0522,
          89
        ]
      },
      "properties": {
        "name": "Los Angeles"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -87.6298,
          41.8781,
          182
        ]
      },
      "properties": {
        "name": "Chicago"
      }
    }
  ]
}


## Exercise6: Filter the features from exercise 5 to include only cities with an elevation greater than 50 meters. Use dictionary comprehension for this task.

In [285]:
for feature in feature_collection['features']:
    if feature['geometry']['coordinates'][-1] <= 50:
        feature_collection['features'].remove(feature)
print(json.dumps(feature_collection, indent=2))

{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -118.2437,
          34.0522,
          89
        ]
      },
      "properties": {
        "name": "Los Angeles"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -87.6298,
          41.8781,
          182
        ]
      },
      "properties": {
        "name": "Chicago"
      }
    }
  ]
}


In [286]:
# check the feature count after filtering
print(f"\nThe number of features are {len(feature_collection['features'])}.")


The number of features are 2.


## Exercise7: MultiPoint Feature
Create a MultiPoint feature from the locations of three major tech company headquarters: Apple (-122.0312, 37.3318), Google (-122.0842, 37.4220), and Facebook (-122.1484, 37.4848). Add a property "name" with the value "Tech Giants HQ".

In [287]:
name = 'Tech Giants HQ'
coords = [[lon, lat] for lon, lat in [(-122.0312, 37.3318), (-122.0842, 37.4220), (-122.1484, 37.4848)]]

multipoint_feature_template = {
    'type': 'Feature',
    'geometry':{
        'type': 'MultiPoint',
        'coordinates': coords # same array structure [ [lon,lat], [lon,lat], ... ] as LineString
    },
    'properties':{
        'name': name
    }
}

print(multipoint_feature_template)

{'type': 'Feature', 'geometry': {'type': 'MultiPoint', 'coordinates': [[-122.0312, 37.3318], [-122.0842, 37.422], [-122.1484, 37.4848]]}, 'properties': {'name': 'Tech Giants HQ'}}


## Exercise8: generate_point_geojson()
Create a function to generate a GeoJSON Point feature, then use it with dictionary comprehension to create features for these world cities (include country and population as properties):

Tokyo (139.6917, 35.6895), Japan, 37,400,000
Delhi (77.1025, 28.7041), India, 31,399,000
Shanghai (121.4737, 31.2304), China, 27,058,000


In [288]:
def generate_point_geojson(cityName, coords, country, pop):
    feature_template = {
        'type': 'Feature',
        'geometry': {
            'type': 'Point',
            'coordinates': [coords[0], coords[1]]
        },
        'properties':{
            'name': cityName,
            'country': country,
            'population': pop
        }
    }
    return feature_template

In [289]:
# run the function to create Point features

tokyo = generate_point_geojson('Tokyo', (139.6917, 35.6895), 'Japan', 37400000)
delhi = generate_point_geojson('Delhi', (77.1025, 28.7041), 'India', 31399000)
shanghai = generate_point_geojson('Shanghai', (121.4737, 31.2304), 'China', 27058000)

feature_collection2 = {
    'type': 'FeatureCollection',
    'features': [obj for obj in [tokyo, delhi, shanghai]]
}

In [290]:
print(json.dumps(feature_collection2, indent=2))

{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          139.6917,
          35.6895
        ]
      },
      "properties": {
        "name": "Tokyo",
        "country": "Japan",
        "population": 37400000
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          77.1025,
          28.7041
        ]
      },
      "properties": {
        "name": "Delhi",
        "country": "India",
        "population": 31399000
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          121.4737,
          31.2304
        ]
      },
      "properties": {
        "name": "Shanghai",
        "country": "China",
        "population": 27058000
      }
    }
  ]
}


## Exercise9:  FeatureCollection
Combine the GeoJSON objects from exercises 1, 3, 4, and 7 into a single FeatureCollection. Add the world cities from exercise 8 to this collection as well.

In [291]:
Feature_list = [point_feature_template, LineString_feature_template, polygon_feature_template, multipoint_feature_template]
# add world cities from exercise 8
Feature_list.extend([tokyo, delhi, shanghai])

feature_collection3 = {
    'type': 'FeatureCollection',
    'features': Feature_list
}

print(json.dumps(feature_collection3, indent=2))
# # update the object's feature
# feature_collection3['features']= Feature_list
# 
# print(json.dumps(feature_collection3, indent=2))

{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -122.4194,
          37.7749
        ]
      },
      "properties": {
        "name": "San Francisco",
        "country": "USA"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -122.4194,
            37.7749
          ],
          [
            -74.006,
            40.7128
          ],
          [
            -0.1276,
            51.5074
          ]
        ]
      },
      "properties": {
        "name": "International Flight Path"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -122.4194,
              37.7749
            ],
            [
              -122.4099,
              37.7912
            ],
            [
           

In [292]:
len(Feature_list)

7

In [293]:
# Bonus: create a is_geojson(your geojson) function to see if your object has correct Geojson format
def validate_geojson(geojson_obj):
    """
    Validate if an object is a valid GeoJSON object.
    Returns (bool, str): (is_valid, error_message)
    """
    try:
        # Check if it's a dictionary
        if not isinstance(geojson_obj, dict):
            return False, "GeoJSON must be a dictionary"

        # Check if it has a "type" field
        if "type" not in geojson_obj:
            return False, "GeoJSON must have a 'type' field"

        # Validate based on type
        geojson_type = geojson_obj["type"]
        
        if geojson_type == "FeatureCollection":
            return validate_feature_collection(geojson_obj)
        elif geojson_type == "Feature":
            return validate_feature(geojson_obj)
        else:
            return False, f"Unsupported GeoJSON type: {geojson_type}"

    except Exception as e:
        return False, f"Validation error: {str(e)}"

def validate_feature_collection(feature_collection):
    """
    Validate a FeatureCollection object
    """
    # Check if it has features array
    if "features" not in feature_collection:
        return False, "FeatureCollection must have 'features' array"

    features = feature_collection["features"]
    if not isinstance(features, list):
        return False, "'features' must be an array"

    # Validate each feature
    for i, feature in enumerate(features):
        is_valid, error = validate_feature(feature)
        if not is_valid:
            return False, f"Invalid feature at index {i}: {error}"

    return True, "Valid FeatureCollection"

def validate_feature(feature):
    """
    Validate a Feature object
    """
    # Check required fields
    if not isinstance(feature, dict):
        return False, "Feature must be a dictionary"

    if "type" not in feature or feature["type"] != "Feature":
        return False, "Feature must have type 'Feature'"

    if "geometry" not in feature:
        return False, "Feature must have 'geometry' field"

    if "properties" not in feature:
        return False, "Feature must have 'properties' field"

    # Validate geometry
    return validate_geometry(feature["geometry"])

def validate_geometry(geometry):
    """
    Validate a geometry object
    """
    if not isinstance(geometry, dict):
        return False, "Geometry must be a dictionary"

    if "type" not in geometry:
        return False, "Geometry must have 'type' field"

    if "coordinates" not in geometry:
        return False, "Geometry must have 'coordinates' field"

    # Validate based on geometry type
    geom_type = geometry["type"]
    coordinates = geometry["coordinates"]

    try:
        if geom_type == "Point":
            return validate_point_coords(coordinates)
        elif geom_type == "LineString":
            return validate_line_coords(coordinates)
        elif geom_type == "Polygon":
            return validate_polygon_coords(coordinates)
        elif geom_type == "MultiPoint":
            return validate_multi_point_coords(coordinates)
        else:
            return False, f"Unsupported geometry type: {geom_type}"
    except Exception as e:
        return False, f"Invalid coordinates for {geom_type}: {str(e)}"

def validate_point_coords(coords):
    """
    Validate Point coordinates [lon, lat]
    """
    if not isinstance(coords, list) or len(coords) != 2:
        return False, "Point coordinates must be [lon, lat]"
    
    if not all(isinstance(c, (int, float)) for c in coords):
        return False, "Coordinates must be numbers"
        
    lon, lat = coords
    if not (-180 <= lon <= 180 and -90 <= lat <= 90):
        return False, "Invalid longitude/latitude values"
        
    return True, "Valid Point coordinates"

def validate_line_coords(coords):
    """
    Validate LineString coordinates [[lon, lat], ...]
    """
    if not isinstance(coords, list) or len(coords) < 2:
        return False, "LineString must have at least 2 points"
        
    for point in coords:
        is_valid, error = validate_point_coords(point)
        if not is_valid:
            return False, f"Invalid point in LineString: {error}"
            
    return True, "Valid LineString coordinates"

def validate_polygon_coords(coords):
    """
    Validate Polygon coordinates [[[lon, lat], ...]]
    """
    if not isinstance(coords, list) or len(coords) < 1:
        return False, "Polygon must have at least one ring"
        
    for ring in coords:
        if not isinstance(ring, list) or len(ring) < 4:
            return False, "Polygon ring must have at least 4 points"
            
        # Check if ring is closed
        if ring[0] != ring[-1]:
            return False, "Polygon ring must be closed"
            
        for point in ring:
            is_valid, error = validate_point_coords(point)
            if not is_valid:
                return False, f"Invalid point in Polygon: {error}"
                
    return True, "Valid Polygon coordinates"

def validate_multi_point_coords(coords):
    """
    Validate MultiPoint coordinates [[lon, lat], ...]
    """
    if not isinstance(coords, list):
        return False, "MultiPoint coordinates must be an array"
        
    for point in coords:
        is_valid, error = validate_point_coords(point)
        if not is_valid:
            return False, f"Invalid point in MultiPoint: {error}"
            
    return True, "Valid MultiPoint coordinates"

In [294]:
# Example 1 usage:
if __name__ == "__main__":
    # Test with your GeoJSON object
    test_geojson = {
        "type": "FeatureCollection",
        "features": [
            {
                "type": "Feature",
                "geometry": {
                    "type": "Point",
                    "coordinates": [-122.4194, 37.7749]
                },
                "properties": {
                    "name": "San Francisco"
                }
            }
        ]
    }
    
    is_valid, message = validate_geojson(test_geojson)
    print(f"test_geojson- Is valid: {is_valid}")
    print(f"test_geojson- Message: {message}")

test_geojson- Is valid: True
test_geojson- Message: Valid FeatureCollection


In [295]:
# Example 2:
test_geojson1 = {
        "type": "FeatureCollection",
        "features": [
            {
                "type": "Feature",
                "geometry": {
                    "type": "Point",
                    "coordinates": []  # no lon/lat info here
                },
                "properties": {
                    "name": "San Francisco"
                }
            }
        ]
    }
print (f"test_geojson1- ",validate_geojson(test_geojson1))

test_geojson1-  (False, 'Invalid feature at index 0: Point coordinates must be [lon, lat]')


In [296]:
# Example 3 for exercise 9:
print (validate_geojson(feature_collection3))

(True, 'Valid FeatureCollection')


## Exercise10: calculate_bbox()
Calculate the bounding box for the FeatureCollection from exercise 9. The bounding box should be in the format [min_lon, min_lat, max_lon, max_lat].

In [297]:
# Point: [lon, lat]
# MultiPoint: [[lon, lat], [lon, lat], ...]
# LineString: [[lon, lat], [lon, lat], ...]
# MultiLineString: [[[lon, lat], [lon, lat], ...], [[lon, lat], ...]]
# Polygon: [[[lon, lat], [lon, lat], ...]]  # Array of rings
# MultiPolygon: [[[[lon, lat], [lon, lat], ...]], [...]]  # Array of polygons

def calculate_bbox(geojson_obj):
    lon_list = []
    lat_list = []
    for feature in geojson_obj['features']:
        geom_type = feature['geometry']['type']
        coords = feature['geometry']['coordinates']  # a coords list
        if geom_type == "Point":
            lon_list.append(coords[0])
            lat_list.append(coords[1])
        elif geom_type == "MultiPoint" or geom_type == "LineString":
            lon_list_MultiPoint_LineString = [coord[0] for coord in coords]
            lat_list_MultiPoint_LineString = [coord[1] for coord in coords]
            
            lon_list.extend(lon_list_MultiPoint_LineString)
            lat_list.extend(lat_list_MultiPoint_LineString)
        elif geom_type == "Polygon":
            lon_list_Polygon = [coord[0] for coord in coords[0]]
            lat_list_Polygon = [coord[1] for coord in coords[0]]
    
            lon_list.extend(lon_list_Polygon)
            lat_list.extend(lat_list_Polygon)
            
    min_lon = min(lon_list)
    min_lat = min(lat_list)
    max_lon = max(lon_list)
    max_lat = max(lat_list)
    
    return [min_lon, min_lat, max_lon, max_lat]


In [298]:
feature_collection3_bbox = calculate_bbox(feature_collection3)
print (feature_collection3_bbox)

[-122.4194, 28.7041, 139.6917, 51.5074]


## Plot the result

In [299]:
#  Use Terminal to install packages if needed:
#  pip install folium geopandas matplotlib shapely
import folium
from folium import GeoJson

In [300]:
def plot_geojson_with_bbox(geojson_data, bbox):
    """
    Plot GeoJSON and bounding box using folium with simple popups.
    """
    # Create a map centered on the bounding box
    m = folium.Map(tiles='OpenStreetMap')

    # Add GeoJSON features with simple popups
    GeoJson(
        geojson_data,
        popup=folium.GeoJsonPopup(
            fields=['name'],
            aliases=['Name:']
        )
    ).add_to(m)

    # Add bounding box
    bbox_polygon = {
        "type": "Feature",
        "geometry": {
            "type": "Polygon",
            "coordinates": [[
                [bbox[0], bbox[1]],
                [bbox[2], bbox[1]],
                [bbox[2], bbox[3]],
                [bbox[0], bbox[3]],
                [bbox[0], bbox[1]]
            ]]
        }
    }

    # Add bounding box to map with visible style
    GeoJson(
        bbox_polygon,
        style_function=lambda x: {
            'fillColor': 'none',
            'color': 'red',
            'weight': 2
        }
    ).add_to(m)

    # Fit the map to the bounding box
    m.fit_bounds([[bbox[1], bbox[0]], [bbox[3], bbox[2]]])

    # Wrap the map in a centered HTML container
    map_plot = HTML(f"""
        <div style="display: flex; justify-content: center;">
            <div style="width:50%">
                {m._repr_html_()}
            </div>
        </div>
    """)

    return map_plot

In [301]:
map_plot = plot_geojson_with_bbox(feature_collection3, feature_collection3_bbox)
display(map_plot)
# map_plot.save('geojson_with_bbox.html')

### Review: How to merge lists

In [303]:
list1 = [1,2,3]
list_ele_append = [4,5]

list_added = list1 + list_ele_append
list_added

[1, 2, 3, 4, 5]